/*ESSE METODO DA FUNCAO VAI MECHER COM A FOTO QUANDO O MAUSE PASSAR POR CIMA DO ELEMENTO*/
function mudaFoto(foto) {
    document.getElementById("icone").src = foto;
}

/*AQUI EU POSSO CRIAR QUANTAS FUNCOES FOR NECESSARIO COMO NO CSS*/

/*FUNCAO PARA CALCULAR O TOTAL A SER PAGO NA COMPRA DO OCULOS GOOGLE GLASS*/

//A MESMA FUNCAO DO FORMULARIO
function calc_total() {
    /*ESSA VARIAVEL VAI PEGAR O CONTEUDO (id) DA CAIXA DE QUANTIDADE (cQtd). 'value' E PEGAR O VALOR*/

    /*A QUANTIDADE VAI SER UM NUMERO, ENTAO VAI TER QUE CONVERTER O VALOR PARA INTEIRO*/
    const qtd = parseInt(document.getElementById('cQtd').value);

    /*VARIAVEL 'tot' VAI PEGAR O VALOR DA OUTRA VARIAVEL E CALCULAR 1500 NELA QUE CADA UM OCULOS VAI SAIR POR 1500 REAIS*/
    const tot = qtd * 1500;

    /*AQUI VAI MOSTRAR NA CAIXA DE TEXTO QUE FOI TRAVADA O VALOR CALCULADO QUE O 'id' DELA E 'cTot'*/
    document.getElementById('cTot').value = tot;
}